newfile = open('one.txt', 'w')
newfile.write("hello friends")
newfile.write('this is a new line\n')
newfile.write('this is line 2\nnow 3')
newfile.close()
file2 = open('one.txt', 'r')
print file2.read(2)
print file2.readline()
print file2.read()
file2.close()